# Generated by Django 4.2.4 on 2023-08-03 00:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_alter_blog_author'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='blog',
            new_name='Post',
        ),
    ]
